### ISSUE TITLE
Using this package for customer signature capture

### ISSUE THREAD

**Issue by joaopiopedreira** [foxdog-studios/meteor-pixijs#3]
Hi @dj-foxxy,

I'm using plain HTML5 canvas to capture customer (hand written) signatures in my meteor-cordova app. It works well on iOS but is pretty slow on Android (< 4.4.x).

Do you think I could use this package for the same purpose and expect a performance gain?

Many thanks, Joao

**Comment by dj-foxxy** [comment]
It's too difficult to say without knowing more about your use case and seeing your existing code. Is your bottleneck the rendering or handling the touch events?

If rendering, Pixi.js may help but you'd have to invest time learning it. It's probably better to optimize your existing code.

If touch events, Android fires many more touch events than iOS. We implement lots of rate limiting in our apps to prevent jank.

Closing the issue but not the discussion. "Close" always seems rude. I'm just closing it because I don't need to modify the repo but I'm interested in your use case.

Pete.

**Comment by joaopiopedreira** [comment]
Hi Pete,

I'm using the [jSignature](http://willowsystems.github.io/jSignature/#/about/) (jQuery) plugin. It draws directly on the canvas in conventional ways.

How should I go about limiting the rate of touch events in Android? Can you please elaborate?

Many thanks, Joao
